### ISSUE TITLE
Is this gem is dead?

### ISSUE THREAD

**Issue by gkunwar** [zipMoney/zipmoney-ruby-sdk#13]
Hello ZipMoney and @webgig 

I'm using this gem to integrate ZipPay to my site. But this gives unexpected many errors. Does anyone maintaining this gem or not?

If not is there any alternative of this?

My current error is:
`757: unexpected token at '<AuthoriseResponse xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/ZipMoney.Domain.Model.Api"><MerchantId>3854</MerchantId><MerchantKey>TCrDzepzZ4mQWJa9ZOPgzNxYGGfVbmX4YGyYz7KAeVU=</MerchantKey><Version i:nil="true" /><CreateTime>2018-05-20T15:37:47.1368934+10:00</CreateTime><CustomerId i:nil="true" /><Metadata i:nil="true" /><OrderId>1042</OrderId><Reason i:nil="true" /><Reference i:nil="true" /><StaffRefCode i:nil="true" /><Status>New</Status><ZipMoneyRef>160163</ZipMoneyRef><ZipOrderId>0</ZipOrderId><RedirectUrl>https://account.sandbox.zipmoney.com.au/?o=eEVIZ1FTNWlzdWJvdTcyM0J5cWd6Zz09RGhUZ0hYOEU0VlBaWlRmamZDaHJuZz090</RedirectUrl></AuthoriseResponse>'`

**Comment by gkunwar** [comment]
@webgig @zipMoneyBuild I guess previously we got JSON response, and currently we are getting XML response.

**Comment by webgig** [comment]
@gkunwar  A release has been pushed sometime ago that  fixes the issue

**Comment by gkunwar** [comment]
@webgig Thanks for your response. 

The latest codebase is push is about 2 years ago. But I found this problem 3 days. Before 18th May 2018 it was working perfectly. 

Any suggestion or recommendation?

Also can you give me the link of fixes?

**Comment by gkunwar** [comment]
Thank you @webgig and @sagar-zipmoney it is working now. :)
